services:
  - type: web
    name: haven
    env: node
    plan: free
    buildCommand: |
      bun install
      bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
