import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { geoContains, geoNaturalEarth1 } from 'd3-geo';
import { feature } from 'topojson-client';
import world from 'world-atlas/countries-110m.json';

const WIDTH = 640;
const HEIGHT = 330;
const GAP = 8;
const HIGHLIGHT_RADIUS = 3.2;
const padding = Math.max(HIGHLIGHT_RADIUS + 2, GAP / 2);

const normalizeCountry = (value: string | number) =>
  String(value).toLowerCase().replace(/unitedstatesofamerica/g, 'unitedstates').replace(/[^a-z0-9]/g, '');

const collection = feature(world as any, (world as any).objects.countries) as any;
const countries = collection.features as any[];
const projection = geoNaturalEarth1().fitExtent(
  [[padding, padding], [WIDTH - padding, HEIGHT - padding]],
  collection,
);
const groups = new Map<string, { country: string; id: string; coordinates: number[] }>();

for (let y = padding; y <= HEIGHT - padding; y += GAP) {
  for (let x = padding; x <= WIDTH - padding; x += GAP) {
    const coordinates = projection.invert?.([x, y]);
    if (!coordinates) continue;
    const owner = countries.find((country) => geoContains(country, coordinates));
    if (!owner) continue;
    const country = normalizeCountry(owner.properties?.name ?? '');
    const id = normalizeCountry(owner.id ?? '');
    const key = `${country}:${id}`;
    const group = groups.get(key) ?? { country, id, coordinates: [] };
    group.coordinates.push(Number(x.toFixed(2)), Number(y.toFixed(2)));
    groups.set(key, group);
  }
}

const markers: Record<string, [number, number]> = {};
const markerCoordinates: Record<string, [number, number]> = {
  australia: [133.78, -25.27], barbados: [-59.54, 13.19], caymanislands: [-81.25, 19.31],
  cyprus: [33.43, 35.13], germany: [10.45, 51.17], hungary: [19.5, 47.16], ireland: [-8.24, 53.41],
  japan: [138.25, 36.2], luxembourg: [6.13, 49.82], netherlands: [5.29, 52.13], singapore: [103.82, 1.35],
  switzerland: [8.23, 46.82], unitedkingdom: [-3.44, 55.38], unitedstates: [-98.58, 39.83],
};

for (const [country, coordinates] of Object.entries(markerCoordinates)) {
  const point = projection(coordinates);
  if (point) markers[country] = [Number(point[0].toFixed(2)), Number(point[1].toFixed(2))];
}

const source = `// Generated by scripts/generate-map-dots.ts. Do not edit manually.\n` +
  `export const WORLD_MAP_WIDTH = ${WIDTH};\nexport const WORLD_MAP_HEIGHT = ${HEIGHT};\n` +
  `export type WorldMapDotGroup = readonly [country: string, countryId: string, coordinates: readonly number[]];\n` +
  `export const WORLD_MAP_DOT_GROUPS: readonly WorldMapDotGroup[] = ${JSON.stringify([...groups.values()].map(({ country, id, coordinates }) => [country, id, coordinates]))};\n` +
  `export const WORLD_MAP_MARKERS: Readonly<Record<string, readonly [number, number]>> = ${JSON.stringify(markers)};\n`;

if (process.argv.includes('--stdout')) process.stdout.write(source);
else writeFileSync(resolve(import.meta.dir, '../src/data/worldMapDots.ts'), source);
